"""add_digital_twin_layout_and_chatbot_tables

Revision ID: 5ccdf00b5c33
Revises: 200c47f094f0
Create Date: 2026-09-12 14:12:18.365679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccdf00b5c33'
down_revision: Union[str, Sequence[str], None] = '200c47f094f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('x_coord', sa.Float(), nullable=False),
    sa.Column('y_coord', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['parking_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_sensors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('sensor_code', sa.String(length=50), nullable=False),
    sa.Column('sensor_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_ping', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_code')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('parking_slots', sa.Column('x_coord', sa.Float(), nullable=True))
    op.add_column('parking_slots', sa.Column('y_coord', sa.Float(), nullable=True))
    op.add_column('parking_slots', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('parking_slots', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('parking_slots', sa.Column('slot_type', sa.String(length=30), nullable=True))
    op.add_column('parking_zones', sa.Column('x_coord', sa.Float(), nullable=True))
    op.add_column('parking_zones', sa.Column('y_coord', sa.Float(), nullable=True))
    op.add_column('parking_zones', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('parking_zones', sa.Column('height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_zones', 'height')
    op.drop_column('parking_zones', 'width')
    op.drop_column('parking_zones', 'y_coord')
    op.drop_column('parking_zones', 'x_coord')
    op.drop_column('parking_slots', 'slot_type')
    op.drop_column('parking_slots', 'height')
    op.drop_column('parking_slots', 'width')
    op.drop_column('parking_slots', 'y_coord')
    op.drop_column('parking_slots', 'x_coord')
    op.drop_table('chat_messages')
    op.drop_table('parking_sensors')
    op.drop_table('documents')
    op.drop_table('chat_sessions')
    op.drop_table('parking_nodes')
    # ### end Alembic commands ###
