"""add_vehicle_number_and_notification_delivery_channels

Revision ID: 7579d2e740c7
Revises: 5ccdf00b5c33
Create Date: 2026-09-12 23:02:31.673871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7579d2e740c7'
down_revision: Union[str, Sequence[str], None] = '5ccdf00b5c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('delivery_channel', sa.String(length=30), nullable=True))
    op.add_column('notifications', sa.Column('delivery_status', sa.String(length=30), nullable=True))
    op.add_column('visitor_requests', sa.Column('vehicle_number', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitor_requests', 'vehicle_number')
    op.drop_column('notifications', 'delivery_status')
    op.drop_column('notifications', 'delivery_channel')
    # ### end Alembic commands ###
